<?php
/**
 * Web Form Submission Simulation Script
 * Simulates the exact web form submission process
 */

// Load all required dependencies
require_once __DIR__ . '/app/lib/DB.php';
require_once __DIR__ . '/app/lib/SecurityService.php';
require_once __DIR__ . '/app/lib/helpers.php';

// Import functions from App namespace
use function App\{get_user_validation_rules, validate_input, sanitize_input, csrf_field, url, uuid, redirect};
use App\DB;

echo "Web Form Submission Simulation\n";
echo "==============================\n\n";

// Simulate the exact POST data that would come from the web form
$_POST = [
    'name' => 'Test Tally Master',
    'email' => 'tallymaster@test.com',
    'password' => 'TestPass123!',
    'role' => 'tally_master',
    'preferred_name' => 'Test Master',
    'gender' => 'other',
    'pronouns' => 'they/them',
    'csrf_token' => 'test_token' // This would be generated by the form
];

echo "Simulating form submission with data:\n";
foreach ($_POST as $key => $value) {
    echo "  $key: $value\n";
}
echo "\n";

try {
    // Step 1: Check organizer requirement (simulate)
    echo "1. Checking organizer requirement...\n";
    // In real web app, this would check if user is logged in as organizer
    echo "✅ Organizer check passed (simulated)\n";
    
    // Step 2: Check CSRF token (simulate)
    echo "2. Checking CSRF token...\n";
    // In real web app, this would verify the CSRF token
    echo "✅ CSRF check passed (simulated)\n";
    
    // Step 3: Sanitize input data
    echo "3. Sanitizing input data...\n";
    $inputData = sanitize_input($_POST);
    echo "✅ Input data sanitized\n";
    
    // Step 4: Extract variables
    echo "4. Extracting variables...\n";
    $name = $inputData['name'] ?? '';
    $email = $inputData['email'] ?? null;
    $password = $inputData['password'] ?? '';
    $role = $inputData['role'] ?? '';
    $preferredName = $inputData['preferred_name'] ?? $name;
    $gender = $inputData['gender'] ?? null;
    $pronouns = $inputData['pronouns'] ?? null;
    
    echo "✅ Variables extracted:\n";
    echo "  name: $name\n";
    echo "  email: $email\n";
    echo "  role: $role\n";
    echo "  preferred_name: $preferredName\n";
    
    // Step 5: Validate input data
    echo "\n5. Validating input data...\n";
    $validationRules = get_user_validation_rules();
    $validationErrors = validate_input($inputData, $validationRules);
    
    if (!empty($validationErrors)) {
        echo "❌ Validation failed:\n";
        foreach ($validationErrors as $field => $errors) {
            echo "  $field: " . implode(', ', $errors) . "\n";
        }
        exit(1);
    }
    echo "✅ Validation passed\n";
    
    // Step 6: Validate password complexity
    echo "\n6. Validating password complexity...\n";
    if (!empty($password)) {
        if (strlen($password) < 8) {
            echo "❌ Password too short\n";
            exit(1);
        }
        if (!preg_match('/[A-Z]/', $password)) {
            echo "❌ Password missing uppercase\n";
            exit(1);
        }
        if (!preg_match('/[a-z]/', $password)) {
            echo "❌ Password missing lowercase\n";
            exit(1);
        }
        if (!preg_match('/[0-9]/', $password)) {
            echo "❌ Password missing number\n";
            exit(1);
        }
        if (!preg_match('/[^A-Za-z0-9]/', $password)) {
            echo "❌ Password missing symbol\n";
            exit(1);
        }
    }
    echo "✅ Password complexity validation passed\n";
    
    // Step 7: Check password requirement for role
    echo "\n7. Checking password requirement for role...\n";
    if (in_array($role, ['organizer', 'tally_master']) && empty($password)) {
        echo "❌ Password required for role: $role\n";
        exit(1);
    }
    echo "✅ Password requirement check passed\n";
    
    // Step 8: Database operations
    echo "\n8. Performing database operations...\n";
    $pdo = DB::pdo();
    echo "✅ Database connection successful\n";
    
    $pdo->beginTransaction();
    echo "✅ Transaction started\n";
    
    try {
        $userId = uuid();
        $passwordHash = !empty($password) ? password_hash($password, PASSWORD_DEFAULT) : null;
        
        echo "✅ User ID generated: $userId\n";
        echo "✅ Password hash created\n";
        
        // Create user (exactly as controller does)
        $stmt = $pdo->prepare('INSERT INTO users (id, name, email, password_hash, role, preferred_name, gender, pronouns) VALUES (?, ?, ?, ?, ?, ?, ?, ?)');
        $stmt->execute([$userId, $name, $email, $passwordHash, $role, $preferredName, $gender, $pronouns]);
        echo "✅ User created in database\n";
        
        $pdo->commit();
        echo "✅ Transaction committed\n";
        
        // Verify user was created
        $stmt = $pdo->prepare("SELECT * FROM users WHERE id = ?");
        $stmt->execute([$userId]);
        $user = $stmt->fetch(PDO::FETCH_ASSOC);
        
        if ($user) {
            echo "✅ User verification successful:\n";
            echo "  ID: " . $user['id'] . "\n";
            echo "  Name: " . $user['name'] . "\n";
            echo "  Role: " . $user['role'] . "\n";
            echo "  Email: " . $user['email'] . "\n";
            echo "  Preferred Name: " . $user['preferred_name'] . "\n";
        } else {
            echo "❌ User verification failed\n";
        }
        
        // Clean up test user
        $stmt = $pdo->prepare("DELETE FROM users WHERE id = ?");
        $stmt->execute([$userId]);
        echo "✅ Test user cleaned up\n";
        
    } catch (Exception $e) {
        $pdo->rollBack();
        echo "❌ Database operation failed: " . $e->getMessage() . "\n";
        throw $e;
    }
    
    echo "\n🎉 Web form submission simulation successful!\n";
    echo "✅ All steps completed successfully\n";
    echo "✅ User creation process works exactly as expected\n";
    echo "✅ The issue is likely in the web form submission or routing\n";
    
} catch (Exception $e) {
    echo "❌ Web form submission simulation failed: " . $e->getMessage() . "\n";
    echo "Stack trace:\n" . $e->getTraceAsString() . "\n";
}
